
// // @ts-ignore
// import "./globals.css";
// import type { Metadata } from "next";
// import { Geist, Geist_Mono, Poppins } from "next/font/google";
// import Script from "next/script";
// import { CreateProvider } from "./context/CreateContext";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// const poppins = Poppins({
//   variable: "--font-poppins",
//   subsets: ["latin"],
//   weight: ["300", "400", "500", "600", "700", "800"],
// })

// export const metadata: Metadata = {
//   title: "PassATS",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <head>
//         <Script
//           src="https://checkout.razorpay.com/v1/checkout.js"
//           strategy="lazyOnload" 
//         />
//       </head>
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} antialiased font-poppins overflow-x-hidden`}
//       >
//         <CreateProvider>
//           {children}
//         </CreateProvider>
//       </body>
//     </html>
//   );
// }








// @ts-ignore
import "./globals.css";
import type { Metadata } from "next";
import {  Poppins } from "next/font/google";
import Script from "next/script";
import { CreateProvider } from "./context/CreateContext";


const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
})

export const metadata: Metadata = {
  title: "PassATS - AI-Powered Resume Builder That Beats Applicant Tracking Systems",
  description: "Create ATS-optimized resumes that get past automated screening systems. Professional templates, AI suggestions, and keyword optimization to land your dream job.",
  keywords: "resume builder, ATS resume, applicant tracking system, resume optimizer, job application, CV builder, professional resume, AI resume, resume templates, job search, career tools",
  authors: [{ name: "PassATS" }],
  creator: "PassATS",
  publisher: "PassATS",
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  openGraph: {
    type: "website",
    locale: "en_US",
    url: "https://passats.aryuacademy.com/",
    siteName: "PassATS",
    title: "PassATS - AI-Powered Resume Builder That Beats Applicant Tracking Systems",
    description: "Create ATS-optimized resumes that get past automated screening systems. Professional templates, AI suggestions, and keyword optimization.",
    images: [
      {
        url: "https://passats.aryuacademy.com/og-image.jpg",
        width: 1200,
        height: 630,
        alt: "PassATS Resume Builder - Create ATS-Friendly Resumes",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "PassATS - AI Resume Builder",
    description: "Create ATS-optimized resumes that beat automated screening systems",
    images: ["https://passats.aryuacademy.com/og-image.jpg"],
    creator: "@passats",
    site: "@passats",
  },
  viewport: {
    width: "device-width",
    initialScale: 1,
    maximumScale: 5,
  },
  category: "technology",
 
  alternates: {
    canonical: "https://passats.aryuacademy.com/",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Script
          src="https://checkout.razorpay.com/v1/checkout.js"
          strategy="lazyOnload"
        />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <meta name="theme-color" content="#ffffff" />
        <meta name="application-name" content="PassATS" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="default" />
        <meta name="apple-mobile-web-app-title" content="PassATS" />
        <meta name="format-detection" content="telephone=no" />
        <meta name="mobile-web-app-capable" content="yes" />
        <meta name="msapplication-TileColor" content="#ffffff" />
        <meta name="msapplication-tap-highlight" content="no" />
        
        {/* Structured Data for better SEO */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "SoftwareApplication",
              "name": "PassATS Resume Builder",
              "applicationCategory": "BusinessApplication",
              "operatingSystem": "Web",
              "description": "AI-powered resume builder that optimizes for Applicant Tracking Systems",
              "offers": {
                "@type": "Offer",
                "price": "0",
                "priceCurrency": "USD"
              },
              "aggregateRating": {
                "@type": "AggregateRating",
                "ratingValue": "4.8",
                "ratingCount": "1234"
              }
            })
          }}
        />
      </head>
      <body
        className={` ${poppins.variable} antialiased font-poppins overflow-x-hidden`}
      >
        <CreateProvider>
          {children}
        </CreateProvider>
      </body>
    </html>
  );
}